version: '3'
services:
  app:
    image: decidim/decidim:0.29.2
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 3000:3000
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis
    command: bundle exec puma
  sidekiq:
    image: decidim/decidim:0.29.2
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  redis-data: {}